django_project/browser/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    	url(r'^$', views.index, name='index'),
	url(r'^jobs/', views.jobs, name='jobs'),
	url(r'^about', views.about, name='about'),
	url(r'^results/', views.results, name='results'),
	url(r'^complete/(?P<backend>[^/]+)/$', views.AuthComplete.as_view()),
    url(r'^login-error/$', views.LoginError.as_view()),
	url(r'^database/$', views.OrderListJson.as_view(), name='order_list_json'),
	url(r'^pubs/',views.pubDetails, name='publication_details'),
	url(r'^ajax_searchset/$', views.ajax_searchset.as_view(), name='ajax_searchset'),
	url(r'^ajax_compare/$', views.ajax_compare.as_view(), name='ajax_compare'),
]

django_project/melodi/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import logout, login
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from django.core.urlresolvers import reverse_lazy
from browser.views import *
from rest_framework import routers

#routers combine all sorts of things into one simple setup
router = routers.DefaultRouter()
router.register(r'sets', SearchSets, base_name="SetList")
#router.register(r'set', SearchSetDetail, base_name="Set")

urlpatterns = [
	url(r'^api/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	url(r'^api/set/(?P<pk>[0-9]+)/$', SearchSetDetail.as_view()),

    #url(r'^browser/', include('browser.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('social_auth.urls')),
    url(r'^about', about, name='about'),
    url(r'^citation', citation, name='citation'),
    url(r'^help', help, name='help'),
    url(r'^contact', contact, name='contact'),
    url(r'^logout/', logout, {'next_page': reverse_lazy('home')}, name='logout'),
    url(r'^login/', login, name='login'),
    #url(r'^login-error/$', TemplateView.as_view(template_name="login-error.html")),
    url(r'^$', index, name='home'),
    url(r'^jobs/', jobs, name='jobs'),
    url(r'^results/(?P<num>[0-9a-z-]+)/$', results, name='results'),
    url(r'^complete/(?P<backend>[^/]+)/$', AuthComplete.as_view()),
    url(r'^login-error/$', LoginError.as_view()),
    url(r'^database/$', OrderListJson.as_view(), name='order_list_json'),
    url(r'^pubs/(?P<num>[0-9]+_[0-9])/$',pubDetails, name='pubs'),
	url(r'^pubss/(?P<num>.*_[0-9]+_[0-9])/$',pubSingle, name='pubss'),
    url(r'^ajax_searchset/$', ajax_searchset.as_view(), name='ajax_searchset'),
    url(r'^ajax_compare/$', ajax_compare.as_view(), name='ajax_compare'),
    url(r'^get_semmed_items/',get_semmed_items, name='get_semmed_items'),
    url(r'^articles/(?P<num>[0-9]+)/$',articleDetails, name='articles'),
    url(r'^ajax_overlap/$', ajax_overlap.as_view(), name='ajax_overlap'),
	url(r'^dt_test_page/$', dt_test_page, name='dt_test_page'),
    url(r'^ajax_graph_metrics/$', ajax_graph_metrics, name='ajax_graph_metrics'),
    url(r'^ajax_share/$', ajax_share, name='ajax_share'),
    url(r'^ajax_delete/$', ajax_delete, name='ajax_delete'),
    url(r'^download_result/$', download_result, name='download_result'),
    url(r'^download_filter/$', download_filter, name='download_filter'),
    url(r'^upload_filter/$', upload_filter, name='upload_filter'),
    url(r'^save_filter/$', save_filter, name='save_filter'),
    url(r'^temmpo/$', temmpo, name='temmpo'),
    url(r'^temmpo_res/$', temmpo_res, name='temmpo_res')
]

django_project/browser/forms.py
from django import forms
from .models import SearchSet
from django.forms import ModelForm, Textarea, HiddenInput

COMTYPES=(
	('meshMain','Main Mesh'),
	#('notMeshMain', 'Not Main Mesh'),
	('semmed_c','SemMedDB Concept'),
	('semmed_t','SemMedDB Triple')

)

class ComSearchSets(forms.Form): #Note that it is not inheriting from forms.ModelForm
	a = forms.CharField(max_length=200,widget=forms.HiddenInput(),required=False,error_messages={'required': 'Error - Please ensure you have created at least two article sets and then select two from the table below'})
	#change required to False if want to permit analysis on one article set
	b = forms.CharField(max_length=200,widget=forms.HiddenInput(),required=True,error_messages={'required': 'Error - Please ensure you have created at least two article sets and then select two from the table below'})
	comType = forms.MultipleChoiceField(required=True,widget=forms.CheckboxSelectMultiple(attrs={'checked' : 'checked'}), choices=COMTYPES, error_messages={'required': 'Please select at least one search option'})

class CreateSearchSet(forms.ModelForm):
	class Meta:
		model = SearchSet
		fields = ['job_name','user_id','ss_file','ss_desc']
		widgets = {
			'job_name': Textarea(attrs={'cols': 25, 'rows': 1, 'placeholder':'e.g. bmi_medline'}),
            'ss_desc': Textarea(attrs={'cols': 45, 'rows': 1,'placeholder':'e.g. BMI Pubmed search'}),
			'user_id': HiddenInput()
        }

class CreateSemSet(forms.ModelForm):
	class Meta:
		model = SearchSet
		fields = ['job_name','ss_desc','user_id']
		widgets = {
			'job_name': Textarea(attrs={'cols': 25, 'rows': 1, 'placeholder':'e.g. bmi_semmed'}),
            'ss_desc': Textarea(attrs={'cols': 35, 'rows': 1, 'class': 'ui-widget','id':'tags','placeholder':'e.g. body mass index'}),
			'user_id': HiddenInput()
        }

class CreatePubSet(forms.ModelForm):
	class Meta:
		model = SearchSet
		fields = ['job_name','ss_desc','user_id']
		widgets = {
			'job_name': Textarea(attrs={'cols': 25, 'rows': 1, 'placeholder':'e.g. bmi_pubmed'}),
            'ss_desc': Textarea(attrs={'cols': 85, 'rows': 1,'placeholder':'e.g. body mass index'}),
			'user_id': HiddenInput()
        }

django_project/browser/views.py
import sys
import gzip
import time
import numpy
import json
import time
import logging
import operator
import config
import csv
import StringIO
import subprocess
import HTMLParser

#from py2neo import Graph, Path, Node, Relationship,authenticate
from scipy import stats

from django.shortcuts import render_to_response
from django.shortcuts import get_object_or_404, render
from browser.forms import (CreateSemSet,ComSearchSets,CreateSearchSet,CreatePubSet)
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.template import RequestContext
#from browser.medline_parser import *
from browser.tasks import *
from browser.models import SearchSet,Compare,Overlap,Filters
from django.template.defaulttags import register
#from django.template.context_processors import csrf
from django.shortcuts import redirect
from django.core.exceptions import ObjectDoesNotExist
from math import exp
from django_datatables_view.base_datatable_view import BaseDatatableView
from collections import defaultdict
from django.views.decorators.csrf import csrf_exempt
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from django.core.serializers.json import DjangoJSONEncoder
from django.core import serializers
from sets import Set
from settings import DATA_FOLDER

#neo4j
from neo4j.v1 import GraphDatabase,basic_auth
auth_token = basic_auth(config.user, config.password)
driver = GraphDatabase.driver("bolt://"+config.server+":"+config.port,auth=auth_token)
#logger.debug(config.server)

#===============GoogleAuth Start
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.views.generic.base import View
from social_auth.backends import AuthFailed
from social_auth.views import complete
from django.contrib.auth.decorators import login_required
from django.conf import settings

#rest API
from rest_framework import viewsets
from rest_framework.views import APIView
from browser.serializers import SearchSetSerializer
from rest_framework.response import Response
from django.http import Http404


#logging.basicConfig(format='%(asctime)s %(message)s', datefmt='%m/%d/%Y %I:%M:%S %p',level=logging.WARNING)
#logger = logging.getLogger(__name__)
#logging.basicConfig(filename='run.log',level=logging.DEBUG)

class SearchSets(viewsets.ModelViewSet):
	"""
	Retrieve all article sets for a user.
	"""

	serializer_class = SearchSetSerializer

	def get_queryset(self):
		user = self.request.user
		logger.debug('user.id = '+str(user.id))
		return SearchSet.objects.filter(user_id=str(user.id))
		#return SearchSet.objects.all()

	def create(self, request):
		logger.debug('post')
		serializer = SearchSetSerializer(data=request.data)
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data)
		#api_result = sets_list.create_new_set(request.data)
		#return Response(api_result)

class SearchSetDetail(APIView):
	"""
	Retrieve, update or delete an article set instance.
	"""
	#serializer_class = SearchSetSerializer

	def get_object(self,pk):
		set_id = self.kwargs['pk']
		user = self.request.user
		logger.debug('user:'+str(user.id)+' set_id:'+str(set_id))
		try:
			#user = self.request.user
			o = SearchSet.objects.get(id=str(set_id),user_id=str(user.id))
			#for i in o:
			#	logger.debug(i.ss_desc)
			#logger.debug(o)
			return o
		except SearchSet.DoesNotExist:
			raise Http404

	def get(self, request, pk, format=None):
		snippet = self.get_object(pk)
		serializer = SearchSetSerializer(snippet)
		logger.debug(serializer)
		return Response(serializer.data)

	def put(self, request, pk, format=None):
		snippet = self.get_object(pk)
		serializer = SearchSetSerializer(snippet, data=request.data)
		if serializer.is_valid():
			serializer.save()
			return Response(serializer.data)
		return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
	#
	def delete(self, request, pk, format=None):
		snippet = self.get_object(pk)
		snippet.delete()
		return Response(status=status.HTTP_204_NO_CONTENT)


class AuthComplete(View):
    def get(self, request, *args, **kwargs):
		logging.warning('error')
		backend = kwargs.pop('backend')
		try:
			return complete(request, backend, *args, **kwargs)
		except AuthFailed:
			logging.warning('error')
			messages.error(request, "Your Google Apps domain isn't authorized for this app")
			return HttpResponseRedirect(reverse('gauth_login'))

class LoginError(View):
    def get(self, request, *args, **kwargs):
        return HttpResponse(status=401)

#===============GoogleAuth End

@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)
@register.filter
def mysplit(value, sep = "."):
    parts = value.split(sep)
    return (parts)

tmpDir=settings.MEDIA_ROOT

def people(request):
	#example query
	sem="match (s:SearchSet)--(p:Pubmed)--(st:SDB_triple)--(si:SDB_item) where s.name = 'tom gaunt_2' return count(distinct(p)) as c,si order by c;"
	mesh="match (s:SearchSet)--(p:Pubmed)--(m:Mesh) where s.name = 'tom gaunt_2' return count(distinct(p)) as c,m order by c;"


def ajax_graph_metrics(request):
	session = driver.session()
	logger.debug('getting graph metrics')
	uAll=SearchSet.objects.order_by().values_list('user_id',flat=True).exclude(user_id='2').distinct().count()
	if request.is_ajax():
		# get data for graph
		# only want search sets that I (user 2) haven't created
		#gCom = "match (s:SearchSet) where not s.name =~ '.*_2' return count(s) as s union match (s:Pubmed) return count(s) as s union match (s:Mesh) return count(s) as s union match (s:SDB_triple) return count(s) as s union match (s:SDB_item) return count(s) as s;"
		gCom = "match (s:Pubmed) return count(s) as s union match (s:Mesh) return count(s) as s union match (s:SDB_triple) return count(s) as s union match (s:SDB_item) return count(s) as s;"
		logger.debug(gCom)
		#data = [int(uAll)]
		data = []
		for res in session.run(gCom):
			data.append(res[0])
		metrics = data
		logger.debug(data)

		# get user and article set over time
		# select user_id,job_start from browser_searchset where user_id != 2 and job_status = 'Complete';
		logger.debug("getting time data...")
		s = SearchSet.objects.filter(job_status='Complete').exclude(user_id='2')
		tData = []
		aDic = {}
		for i in s:
			u = i.user_id
			t = i.job_start.split(" ")[0].split("-")[0:2]
			t = "-".join(t)
			if t in aDic:
				aDic[t].append(u)
			else:
				aDic[t] = [u]
		c = Compare.objects.filter(job_status='View results').exclude(user_id='2')
		cDic = {}
		for i in c:
			#id = i.id
			id = i.job_name
			t = i.job_start.split(" ")[0].split("-")[0:2]
			t = "-".join(t)
			if t in cDic:
				cDic[t].append(id)
			else:
				cDic[t] = [id]

		cats = []
		uCounts = []
		aCounts = []
		cCounts = []
		cCountOld = []
		oldCount = []
		for a in sorted(aDic):
			cats.append(a)
			#logger.debug(a)
			if a in aDic:
				uCount = len(list(set(aDic[a] + oldCount)))
				uCounts.append(uCount)

				aCount = len(aDic[a] + oldCount)
				aCounts.append(aCount)
				oldCount = aDic[a] + oldCount
			else:
				uCounts.append(0)
				aCounts.append(0)
			if a in cDic:
				cCount = len(list(set(cDic[a] + cCountOld)))
				cCounts.append(cCount)
				cCountOld = cDic[a] + cCountOld
			else:
				cCounts.append(0)
		lastTop=12
		uCounts = uCounts[-lastTop:len(uCounts)]
		aCounts = aCounts[-lastTop:len(aCounts)]
		cCounts = cCounts[-lastTop:len(cCounts)]
		cats = cats[-lastTop:len(cats)]
		#logger.debug(uCounts)

	else:
		data = 'fail'
		logger.debug('not ajax request')
	mimetype = 'application/json'
	session.close()
	return HttpResponse(json.dumps({'metrics':metrics,'uCounts':uCounts,'aCounts':aCounts,'cCounts':cCounts,'cats':cats}), mimetype)


def ajax_test(request):
	object = ''
	f = tmpDir+'/new.txt'
	logger.debug('looking for file ',f)
	if os.path.isfile(f):
		object = "file exists"
		logger.debug('object exists')
	return HttpResponse(object)

def issn_to_name(iList):
	logger.debug('Running issn_to_name'+str(iList))
	#check for null entries
	if 'null' in iList:
		iList.remove('null')
	iString = ",".join(iList)
	start=time.time()
	print "\n### Getting ids ###"
	url="http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?"
	#params = {'term': '0140-6736+OR+0022-2275'}
	params = {'term': iString}

	r = requests.post(url)

	# GET with params in URL
	r = requests.get(url, params=params)

	#create random file name
	n = 10
	ran=''.join(["%s" % randint(0, 9) for num in range(0, n)])
	rSplit = r.text.split("<")

	iDic = {}
	iName = []
	for i in rSplit:
		l = re.match(r'To>(.*?)$', i)
		if l:
			m = l.group(1).replace('[Journal]','').replace('"','').strip().encode("ascii")
			iName.append(m)

	for i in range(0,len(iList)):
		iDic[iList[i]]=iName[i]
	logger.debug(iDic)
	return iDic

def pubmed_id_details(pList):
	logger.debub('Getting pubmed info')

def pmid_to_info(pList):
	#logger.debug('Running pmid_to_info'+str(pList))
	iString = ",".join(pList)
	start=time.time()
	print "\n### Getting ids ###"
	url="http://eutils.ncbi.nlm.nih.gov/entrez/eutils/esummary.fcgi?"
	#params = {'term': '0140-6736+OR+0022-2275'}
	params = {'db':'pubmed','id': iString}

	# GET with params in URL
	r = requests.get(url, params=params)

	#print r.text
	rSplit = r.text.split("<")

	ptDic = {}
	pjDic = {}
	t = jt = 'n/a'
	for i in rSplit:
		#print "i",i
		#check pubmed id
		pmid_match = re.match(r'Item Name="pubmed" Type="String">(.*?)$', i)
		if pmid_match:
			pmid = pmid_match.group(1)
			#print pmid

		#get title
		t_match = re.match(r'Item Name="Title" Type="String">(.*?)$', i)
		if t_match:
			t = t_match.group(1)
			#print t

		#get jorunal name
		jt_match = re.match(r'Item Name="FullJournalName" Type="String">(.*?)$', i)
		if jt_match:
			jt =  jt_match.group(1)
			#print jt

		entry_match = re.match(r'/DocSum>', i)
		if entry_match:
			#print "\n"
			ptDic[pmid]=t
			pjDic[pmid]=jt
			jt='n/a'
			t='n/a'

	#print pDic
	return [ptDic,pjDic]

def about(request):
	context = {'nbar': 'about'}

django_project/browser/templates/about.html
{% extends "base_generic.html" %}

{% block title %}About{% endblock %}

{% block content %}
    <br>
    <div class="row">
	<div class="col-md-6">
                <h3>How to use</h3>
                <ol>
                    <li>Create article sets in one of two ways:
                        <ul>
                            <li>Use a PubMed query</li>
                            <li>Upload a set of PubMed IDs, one per line</li>
                        </ul>
                    <li>Once created, select two article sets from table on the home page</li>
                    <li>Choose analysis options and then hit the 'Find Intermediates' button</li>
                </ol>
	
                <br><h3>Graph Metrics</h3>
                    <ul>
                        <li>45 million nodes</li>
                        <li>200 million relationships</li>
                        <li>1.7 billion properties</li>
                    </ul>
                <br><h3>Contact</h3>
		    <p>If you have any questions/suggestions or would like to discuss a particular project in more detail please get in touch at the following address:
                    <ul>
                        <li>melodi@biocompute.org.uk</li>
                    </ul>
					<br><h3>Privacy Statement</h3>
					<p>Any data provided to MELODI is stored and controlled by the University of Bristol only and not passed on to any third party.
					<p>User data is requested to enhance the usability of the site and not for any commercial purposes.
					User accounts are generated solely to provide a user specific analysis environment and improve user experience.
					User accounts are handled through the Google OAuth protocol and passwords are encrypted.
					Any data associated with the creation and analysis of article sets is private unless shared, held in a secure database, and accessible only to the MELODI administrator.

        </div>
        <div class="col-md-6">
                 <div align="center" class="video-container">
			<iframe width="400" height="250" src="https://www.youtube.com/embed/rEjnmXNLkWA" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
		</div>
		<br><img class="center-block" src="/static/browser/img/melodi_overview.png" width='95%'>
        </div>
    </div>

{% endblock %}

django_project/browser/templates/articles.html
{% extends "base_generic.html" %}

{% block scripts %}
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script>
    $(function () {
    $('#container').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: "'{{ ss | safe}}' - Number of articles per year (10 most common journals labelled)"
        },
        xAxis: {
            //categories: ['Apples', 'Oranges', 'Pears', 'Grapes', 'Bananas']
            categories: {{ years | safe}}
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Article number'
            },
            stackLabels: {
                enabled: false,
                style: {
                    fontWeight: 'bold',
                    color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                }
            }
        },
        /*
        legend: {
            align: 'right',
            x: -30,
            verticalAlign: 'bottom',
            y: 25,
            //floating: true,
            backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
            //borderColor: '#CCC',
            //borderWidth: 1,
            shadow: false
        },
        */
        legend:{
            layout: 'vertical',
            align: 'left',
            verticalAlign: 'top',
            floating: true,
            backgroundColor: '#FFFFFF',
            y: 30,
            x: 80,
        },
        tooltip: {
            headerFormat: '<b>{point.x}</b><br/>',
            pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}'
        },
        plotOptions: {
            column: {
                stacking: 'normal',
                dataLabels: {
                    enabled: false,
                    color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white',
                    style: {
                        textShadow: '0 0 3px black'
                    }
                }
            }
        },
        /*
        series: [{
            name: 'John',
            data: [5, 3, 4, 7, 2]
        }, {
            name: 'Jane',
            data: [2, 2, 3, 2, 1]
        }, {
            name: 'Joe',
            data: [3, 4, 4, 2, 5]
        }]
        */
        series: {{ aData | safe}}
    });
});
    </script>
{% endblock %}

{% block title %}Article Set Details{% endblock %}

{% block content %}
    <br>
<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
{% endblock %}

django_project/browser/templates/citation.html
{% extends "base_generic.html" %}

{% block title %}Citation{% endblock %}

{% block content %}
    <br>
    <div class="row">
        <div class="col-md-12">
            <div class="well well-sm">

		<h3>Citation</h3>
		<p>Benjamin Elsworth, Karen Dawe, Emma E Vincent, Ryan Langdon, Brigid M Lynch, Richard M Martin, Caroline Relton, Julian P T Higgins, Tom R Gaunt; MELODI: Mining Enriched Literature Objects to Derive Intermediates, International Journal of Epidemiology, 2018, <a href='https://doi.org/10.1093/ije/dyx251' target='_blank'>https://doi.org/10.1093/ije/dyx251</a>.
		<p><b>Download citation file:</b>

		<p><a href='https://academic.oup.com/ije/downloadcitation/4803214?format=ris'>RIS (Zotero)</a>
		<br><a href='https://academic.oup.com/ije/downloadcitation/4803214?format=ris'>EndNote</a>
		<br><a href='https://academic.oup.com/ije/downloadcitation/4803214?format=bibtex'>BibTex</a>
		<br><a href='https://academic.oup.com/ije/downloadcitation/4803214?format=txt'>Medlars</a>
		<br><a href='https://academic.oup.com/ije/downloadcitation/4803214?format=ris'>ProCite</a>
		<br><a href='https://academic.oup.com/ije/downloadcitation/4803214?format=txt'>RefWorks</a>
		<br><a href='https://academic.oup.com/ije/downloadcitation/4803214?format=ris'>Reference Manager</a>
        </div>
	</div>
    </div>

{% endblock %}

django_project/browser/templates/help.html
{% extends "base_generic.html" %}

{% block scripts %}
   <style>

  ul.nav-pills {
      top: 120px;
      position: fixed;
  }
  div.col-sm-9 div {
      height: 250px;
      font-size: 28px;
  }
  #section1 {color: #fff; background-color: #1E88E5;}
  #section2 {color: #fff; background-color: #673ab7;}
  #section3 {color: #fff; background-color: #ff9800;}
  #section4 {color: #fff; background-color: #00bcd4;}

  @media screen and (max-width: 1010px) {
    #section1, #section2, #section3, #section4  {
        margin-left: 50px;
    }
  }
  </style>
{% endblock %}

{% block title %}Help{% endblock %}

{% block content %}
    <div data-spy="scroll" data-target="#myScrollspy" data-offset="20">
        <div class="row">
            <nav class="col-sm-3" id="myScrollspy">
              <ul class="nav nav-pills nav-stacked">
                <li class="active"><a href="#section1">Section 1</a></li>
                <li><a href="#section2">Section 2</a></li>
                <li><a href="#section3">Section 3</a></li>
                <li><a href="#section4">Section 4</a></li>
              </ul>
            </nav>
            <div class="col-sm-9">
              <div id="section1">
                <h1>Section 1</h1>
                <p>Try to scroll this section and look at the navigation list while scrolling!</p>
              </div>
              <div id="section2">
                <h1>Section 2</h1>
                <p>Try to scroll this section and look at the navigation list while scrolling!</p>
              </div>
              <div id="section3">
                <h1>Section 3</h1>
                <p>Try to scroll this section and look at the navigation list while scrolling!</p>
              </div>
              <div id="section4">
                <h1>Section 4</h1>
                <p>Try to scroll this section and look at the navigation list while scrolling!</p>
              </div>
            </div>
        </div>
    </div>
{% endblock %}

django_project/browser/templates/temmpo.html
{% extends "base_generic.html" %}
{% load humanize %}

{% load staticfiles %}
{% block scripts %}
<script>
    $(document).ready(function () {
    var table = $('#search_sets').DataTable({
                "order": [[1, "desc"]],
                dom: 'frtip',
                lengthChange: false,
                scrollY:        200,
                deferRender:    true,
                scroller:       true
            })


            $('#search_sets tbody').on('click', 'tr', function () {
                var numItems = $('.selected').length
                if (numItems < 3) {
                    d = table.row(this).data()[0]
                    $(this).toggleClass('selected');
                    //check if A again and clear
                    if (d == $('#circle1').text()){
                        //console.log('comA again')
                        $('#circle1').text('?')
                        $('#id_a').val('')
                    }
                    //check if B again and clear
                    else if (d == $('#circle2').text()){
                        $('#circle2').text('?')
                        $('#id_b').val('')
                    }
                    //check if A is empty
                    else if ($('#circle1').text().length < 1 || $('#circle1').text() == '?'){
                        $('#circle1').text(d)
                        $('#as1').val(d)
                    }
                    //check if B is empty
                    else if ($('#circle2').text().length < 1 || $('#circle2').text() == '?'){
                        $('#circle2').text(d)
                        $('#as2').val(d)
                    }else{
                        $(this).removeClass('selected');
                    }
                }
            });
    })
</script>
{% endblock %}

{% block title %}Temmpo{% endblock %}

{% block content %}
    <br>
    <div class="row well">
    <br>
        <form  action="{% url 'temmpo_res' %}" id="temmpo_form" method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="col-md-4 well" style="height:80px">
            Article Set 1 = <b><span name="circle1" value="a" id="circle1">?</span></b><br>
            Article Set 2 = <b><span name="circle2" value="b" id="circle2">?</span></b>
            <input type="hidden" id="as1" name="as1" value="">
            <input type="hidden" id="as2" name="as2" value="">
        </div>
        <div class="col-md-4 well" style="height:80px">
            Upload intermediates <input type="file" name="intFile">
        </div>
        <div class="col-md-4 well" style="height:80px">
            <!--input type="image" src="/static/browser/img/temmpo_logo.png" width="370px" alt="Submit Form" /-->
            <button type="submit" class="btn btn-warning btn-block">TeMMPo ME !!!</button>
        </div>
        </form>
    </div>
    <div class="row well">
        <div class="col-md-12">
            <table id="search_sets" class="display" cellspacing="0" width="100%">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Date added</th>
                    <th>Description</th>
                    <th>Pubmed articles</th>
                </tr>
                </thead>
                <tbody>
                {% for a in s %}
                    <tr>
                        <!--td><a href="/articles/{{a.id}}/">{{ a.job_name }}</a></td-->
                        <td>{{ a.job_name }}</td>
                        <td>{{ a.job_start }}</td>
                        <td>{{ a.ss_desc|truncatechars:40 }}</td>
                        <td>{{ a.pTotal | intcomma}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-4">

        </div>
    </div>
{% endblock %}